FROM bitnami/java:1.8-prod
ADD https://github.com/use-sparingly/keyutil/releases/download/0.4.0/keyutil-0.4.0.jar /keyutil.jar
ADD docker/certs.sh /certs.sh
ADD build/libs/kees-all.jar /app.jar
CMD ["/bin/sh", "-c", "/certs.sh; java -cp /app.jar com.bsycorp.kees.CreateMain"]